# Construindo portas lógicas com operadores lógicos

print("Porta AND")
print(True and True)
print(True and False)
print(False and True)
print(False and False)

print("Porta OR")
print(True or True)
print(True or False)
print(False or True)
print(False or False)

print("Porta NOT")
print(not True)
print(not False)

print("Porta XOR")
print(True != True)
print(True != False)
print(False != True)
print(False != False)

print("Porta NAND")
print(not (True and True))
print(not (True and False))
print(not (False and True))
print(not (False and False))

print("Porta NOR")
print(not (True or True))
print(not (True or False))
print(not (False or True))
print(not (False or False))

print("Porta XNOR")
print(not (True != True))
print(not (True != False))
print(not (False != True))
print(not (False != False))

print("Porta AND com XOR")
print((True and True) != True)
print((True and False) != True)
print((False and True) != True)
print((False and False) != True)

print("Porta OR com XOR")
print((True or True) != True)
print((True or False) != True)
print((False or True) != True)
print((False or False) != True)

print("Porta NOT com XOR")
print(not (True != True) != True)
print(not (True != False) != True)
print(not (False != True) != True)
print(not (False != False) != True)

print("Porta AND com XNOR")
print((True and True) != False)
print((True and False) != False)
print((False and True) != False)
print((False and False) != False)

print("Porta OR com XNOR")
print((True or True) != False)
print((True or False) != False)
print((False or True) != False)
print((False or False) != False)

print("Porta NOT com XNOR")
print(not (True != True) != False)
print(not (True != False) != False)
print(not (False != True) != False)
print(not (False != False) != False)

print("Porta AND com NAND")
print(not (True and True))
print(not (True and False))
print(not (False and True))
print(not (False and False))

print("Porta OR com NAND")
print(not (True or True))
print(not (True or False))
print(not (False or True))
print(not (False or False))

print("Porta NOT com NAND")
print(not not (True and True))
print(not not (True and False))
print(not not (False and True))
print(not not (False and False))

print("Porta AND com NOR")
print(not (True and True))
print(not (True and False))
print(not (False and True))
print(not (False and False))

print("Porta OR com NOR")
print(not (True or True))
print(not (True or False))
print(not (False or True))
print(not (False or False))

print("Porta NOT com NOR")
print(not not (True or True))
print(not not (True or False))
print(not not (False or True))
print(not not (False or False))

print("Porta AND com NOT")
print(not True)
print(not False)

print("Porta OR com NOT")
print(not True)
print(not False)

print("Porta NOT com NOT")
print(not not True)
print(not not False)

print("Porta AND com AND")
print(True and True and True)
print(True and True and False)
print(True and False and True)
print(True and False and False)
print(False and True and True)
print(False and True and False)
print(False and False and True)
print(False and False and False)

print("Porta OR com OR")
print(True or True or True)
print(True or True or False)
print(True or False or True)
print(True or False or False)
print(False or True or True)
print(False or True or False)
print(False or False or True)
print(False or False or False)

# Chega né
